config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'artists#index'
  resources :artists, :songs
                      #controllorName#methodName
  get "artists", to: "artists#index" 
  get "artists/new", to: "artists#new"
  get "artists/:id", to: "artists#show"
  post "artists", to: "artists#create"
  get "artists/:id/edit", to: "artists#edit", as: :artist_edit
  patch "artists/:id", to: "artists#update"
  delete "artists/:id", to: "artists#destroy"
  get "songs/new", to: "songs#new"
  post "songs", to: "songs#create"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
        @artists = Artist.all
    end
    
    def show
        @artist = Artist.find(params[:id])
        @songs = @artist.songs
    end

    def new
        @artist = Artist.new
    end

    def create
        Artist.create(params.require(:artist).permit(:name, :album, :hometown, :img))
        redirect_to artists_path
    end

    def edit
        @artist = Artist.find(params[:id])
    end

    def update
        artist = Artist.find(params[:id])
        artist.update(params.require(:artist).permit(:name, :albums, :hometown, :img))
          
        redirect_to artist
    end

    def destroy
        Artist.find(params[:id]).destroy
      
        redirect_to artists_path
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def new
        @artist = Artist.find(params[:artist_id])
        @song = Song.new
      end

      def create
        puts params
        artist = Artist.find(params[:song][:artist_id])
        Song.create(params.require(:song).permit(:title, :length, :genre, :artist_id))
               
        redirect_to artist
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <div class="input-field col s6">
  	<%= f.label :name, 'Name'%>
  	<%= f.text_field :name%>
  </div>
  <div class="input-field col s6">
  	<%= f.label :album, 'Albums' %>
  	<%= f.text_field :album %>
  </div>
  <div class="input-field col s6">
  	<%= f.label :hometown, 'Hometown' %>
  	<%= f.text_field :hometown %>
  </div>
  <div class="input-field col s6">
  	<%= f.label :img, 'Image' %>
  	<%= f.text_field :img %>
  </div>
  <%= f.submit "Submit", :class => "btn waves-effect waves-light" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit <%= @artist.name %></h1>

<%= render 'artists/form' %>

app/views/artists/index.html.erb
<div class = "container">
<h1 class="text-center">All the Artists</h1>
<%= link_to "Add an Artist", artists_new_path, { :class => "btn btn-primary btn-lg active" } %>
<br><br>


<table class="table table-hover striped bordered">
  <tr>
    <th class="text-center">Artist</th>
    <th class="text-center">Image</th>
    <th class="text-center">Albums</th>
    <th class="text-center">Hometown</th>
    <th class="text-center">Edit</th>
    <th class="text-center">Delete</th>
  </tr>

  <% @artists.each do |artist| %>
      <tr>
        <td class="text-center"><%= link_to artist.name, artist_path(artist) %></td>
        <td class="text-center"><%= image_tag(artist.img, size: "100x100", alt: "Artist Image") %></td>
        <td class="text-center"><%= artist.album %></td>
        <td class="text-center"><%= artist.hometown %></td>
        <td class="text-center"><a class="btn btn-secondary glyphicon glyphicon-edit" href="<%= edit_artist_path(artist) %>" >
    			</a>
    	  </td>
       <td class="text-center"><a class="btn btn-danger" data-confirm="Are you sure you want to delete <%= artist.name %>?" data-method="delete" href="/artists/<%= artist.id %>" rel="nofollow"><i class="large material-icons">Delete Artist</i>
    	   </a>
        </td>
      </tr>
  <% end %>
</table>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'artists/form' %>

app/views/artists/show.html.erb
  <h1><%= @artist.name %> Songs</h1>
  <%= link_to "New Song", new_song_path(:artist_id => @artist.id), { :class => "button waves-effect waves-light btn" } %>
  <br><br>

  <div class="row">
    <% @songs.each do |song| %>

        <div class="card-panel grey lighten-2 col s4" style="margin: 10px">
          <%= image_tag(@artist.img, size: "100x100", alt: "Artist Image") %>
          <br>
          <strong><%= link_to song.title %></strong>
          <em><%= song.gender %></em>
        </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <%= f.hidden_field :artist_id, :value => @artist.id %>
  <div class="input-field col s6">
  	<%= f.label :title, 'Title' %>
  	<%= f.text_field :title %>
  </div>
  <div class="input-field col s6">
  	<%= f.label :gender, 'Genre' %>
  	<%= f.text_field :gender %>
  </div>
  <%= f.submit "Submit", :class => "btn waves-effect waves-light" %>
<% end %>

app/views/songs/new.html.erb
<h1>New Song for <%= @artist.name %></h1>
<%= link_to "New Song", new_song_path(:artist_id => @artist.id), { :class => "button waves-effect waves-light btn" } %>

<%= render 'songs/form' %>